version: '3.8'

services:
  vueapp_test_e2e:
    networks:
      - fullstack # internally connects to backend for e2e tests
    build:
      context: ./frontend
      dockerfile: ./cypress.Dockerfile
    environment:
      - CYPRESS_VIDEO=${CYPRESS_VIDEO-true}
      - CYPRESS_TAGS=${CYPRESS_TAGS}
      # - CYPRESS_VERIFY_TIMEOUT=100000 # Enable for local test run due to docker slowing down system
      - CYPRESS_ENV_FILE=${CYPRESS_ENV_FILE}
      - CYPRESS_MAILSLURP_API_KEY=${CYPRESS_MAILSLURP_API_KEY}
    depends_on:
      - fastapi
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tests:/app/tests
