version: '3.8'

services:
  mysql_db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    secrets:
      - mysql-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    profiles:
      - backend-serve
      - backend-test
      - fullstack-serve
      - fullstack-e2e-test
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/${MYSQL_DOCKER_VOLUME-mysql}

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: db/mysql_pwd.txt
