version: '3.8'

services:
  fastapi:
    restart: always
    tty: true # enables colored log # docker run -t
    stdin_open: false # enables colored log # docker run -i
    build:
      context: ./src/
    networks:
      - backend
      - fullstack
      - traefik-public
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - ${API_SERVER_PORT:-8018}:${SERVER_PORT:-8018}
    volumes:
      - ./src:/app
    secrets:
      - mysql-password
    environment:
      - DATABASE_URL=${DATABASE_URL:-mysql://root@mysql_db/login}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - CORS_ORIGINS_SET=${CORS_ORIGINS_SET:-Development}
      - SECURE_COOKIES=${SECURE_COOKIES:-False}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 256M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 128M
