version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-password
      - MONGO_INITDB_DATABASE=login
    secrets:
      - mongo-password
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/login --quiet
      # interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - backend
      - fullstack
      - traefik-public
    volumes:
      - mongo-data:/var/lib/${MONGO_DOCKER_VOLUME-mongo}

volumes:
  mongo-data:

secrets:
  mongo-password:
    file: db/mongo_pwd.txt
