version: '3.8'

services:
  vueapp_test_e2e:
    networks:
      - fullstack # internally connects to backend for e2e tests
    build:
      context: ./frontend
      dockerfile: ./cypress.Dockerfile
    secrets:
      - mailslurp_api_key
    environment:
      - CYPRESS_VIDEO=${CYPRESS_VIDEO-true}
      - CYPRESS_TAGS=${CYPRESS_TAGS}
      - CYPRESS_VERIFY_TIMEOUT=${CYPRESS_VERIFY_TIMEOUT}
      - CYPRESS_MAILSLURP_API_KEY=${CYPRESS_MAILSLURP_API_KEY}
      - CYPRESS_ENV_FILE=${CYPRESS_ENV_FILE}
      - CYPRESS_ADMIN_API_LOGIN_USERNAME=${CYPRESS_ADMIN_API_LOGIN_USERNAME}
      - CYPRESS_ADMIN_API_LOGIN_PASSWORD=${CYPRESS_ADMIN_API_LOGIN_PASSWORD}
    depends_on:
      - fastapi
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tests:/app/tests

secrets:
  mailslurp_api_key:
    file: frontend/docker_secrets/mailslurp_api_key.txt
