
version: '3.8'

services:
  vueapp:
    depends_on:
      - fastapi
    build:
      context: ./frontend
      target: serve-local-stage
    restart: always
    volumes:
      - ./frontend/src:/app/src # live reload
      - ./frontend/tests:/app/tests # live reload
    ports:
      - 8019:8080
