version: '3.8'

services:

  fastapi_test:
    extends:
      file: compose.fastapi.service.yml
      service: fastapi_test_base
    profiles:
      - backend-test
    networks:
      - backend
    depends_on:
      mysql_db:
        condition: service_healthy
    secrets:
      - mysql-password

  fastapi_test_sqlite:
    extends:
      file: compose.fastapi.service.yml
      service: fastapi_test_base
    profiles:
      - backend-test-sqlite
    networks:
      - backend
    secrets:
      - mysql-password

  mysql_db:
    extends:
      file: compose.mysql.service.yml
      service: mysql_db_base
    profiles:
      - fullstack-e2e-test
      - backend-test
    networks:
      - backend

networks:
  backend:

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: db/mysql_pwd.txt