version: '3.8'

services:
  fastapi_serve:
    extends:
      file: compose.fastapi.service.yml
      service: fastapi_serve_base
    profiles:
      - backend-serve
      - fullstack-serve
    networks:
      - fullstack
      - backend
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - ${API_SERVER_PORT:-8018}:${SERVER_PORT:-8018}
    secrets:
      - mysql-password

  fastapi_serve_sqlite:
    extends:
      file: compose.fastapi.service.yml
      service: fastapi_serve_base_compact
    profiles:
      - backend-serve-sqlite
    networks:
      - backend
    ports:
      - ${API_SERVER_PORT:-8018}:${SERVER_PORT:-8018}

  mysql_db:
    extends:
      file: compose.mysql.service.yml
      service: mysql_db_base
    profiles:
      - backend-serve
      - fullstack-serve
    networks:
      - backend

  vueapp_serve_dev:
    profiles:
      - fullstack-serve
    networks:
      - fullstack
    depends_on:
      - fastapi_serve
    build:
      context: ./frontend
      target: serve-dev-stage
    volumes:
      - ./frontend/src:/app/src # live reload
    ports: 
      - 8019:8080

networks:
  fullstack:
  backend:

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: db/mysql_pwd.txt