version: '3.8'

services:

  fastapi_serve:
    profiles:
      - fullstack-e2e-test
    networks:
      - fullstack
      - backend
    build:
      context: ./src/
      target: serve-stage
    restart: always
    environment:
      - ENV_FILE=.test.env
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - ./src:/app
    secrets:
      - mysql-password

  fastapi_test:
    profiles:
      - backend-test
    networks:
      - backend
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./src/
      target: test-stage
    restart: always
    environment:
      - ENV_FILE=.test.env
    volumes:
      - ./src:/app
    secrets:
      - mysql-password

  mysqldb:
    profiles:
      - fullstack-e2e-test
      - backend-test
    networks:
      - backend
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    secrets:
      - mysql-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  vueapp_test_e2e:
    profiles:
      - fullstack-e2e-test
    networks:
      - fullstack
    depends_on:
      - fastapi_serve
    build:
      context: ./frontend
      dockerfile: ./cypress.Dockerfile
      target: test-e2e-stage
    environment:
      - VUE_APP_BACKEND_URL=http://fastapi_serve:8018
    volumes:
      - ./frontend/src:/app/src # live reload
      - ./frontend/tests:/app/tests # live reload

networks:
  fullstack:
  backend:

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: db/mysql_pwd.txt