version: '3.8'

services:

  fastapi_serve:
    profiles:
      - backend-serve
      - fullstack-serve
      - fullstack-e2e-test
    networks:
      - fullstack
      - backend
    build:
      context: ./src/
      target: serve-stage
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 8018:8018
    volumes:
      - ./src:/app
    secrets:
      - mysql-password

  fastapi_test:
    profiles:
      - backend-test
    networks:
      - backend
    depends_on:
      mysqldb:
        condition: service_healthy
    build: 
      context: ./src/
      target: test-stage
    restart: always
    ports:
      - 8018:8018
    volumes:
      - ./src:/app
    secrets:
      - mysql-password

  mysqldb:
    profiles:
      - backend-serve
      - fullstack-serve
      - fullstack-e2e-test
      - backend-test
    networks:
      - backend
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  vueapp_serve_dev:
    profiles:
      - fullstack-serve
    networks:
      - fullstack
    depends_on:
      - fastapi_serve
    build:
      context: ./frontend
      target: serve-dev-stage
    volumes:
      - ./frontend/src:/app/src # live reload
    ports: 
      - 8019:8080

  vueapp_test_e2e_dev:
    profiles:
      - fullstack-e2e-test
    networks:
      - fullstack
    depends_on:
      - fastapi_serve
    build:
      context: ./frontend
      dockerfile: ./cypress.Dockerfile
      target: test-e2e-dev-stage
    volumes:
      - ./frontend/src:/app/src # live reload
      - ./frontend/tests:/app/tests # live reload

networks:
  fullstack:
  backend:

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: db/mysql_pwd.txt