version: '3.8'

services:
  mysqldb_base:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
