"""user_session index max length

Revision ID: 005fa1e3ca77
Revises: 19144ec6e66f
Create Date: 2022-09-01 02:24:37.989453

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '005fa1e3ca77'
down_revision = '19144ec6e66f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_token', 'user_sessions', ['token'], unique=False, mysql_length=1024)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token', table_name='user_sessions', mysql_length=1024)
    # ### end Alembic commands ###
