"""second commit

Revision ID: 12114d778a07
Revises: 940bc2e1b3fc
Create Date: 2022-08-15 10:01:22.978061

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '12114d778a07'
down_revision = '940bc2e1b3fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_verifications', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_email_verifications', 'expires_at')
    # ### end Alembic commands ###
