"""added fields: name, profile_pic in user table

Revision ID: 5533cdeeabed
Revises: 16c5e662fae1
Create Date: 2023-04-25 19:04:03.604995

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "5533cdeeabed"
down_revision = "16c5e662fae1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=128), nullable=True))
    op.add_column(
        "users", sa.Column("profile_picture", sa.String(length=256), nullable=True)
    )
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_column("users", "profile_picture")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
