"""add cascade delete for email verifications table, field user_id for when user is deleted

Revision ID: b55b53f8fcda
Revises: f66b173d2355
Create Date: 2022-10-05 23:29:39.240381

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b55b53f8fcda'
down_revision = 'f66b173d2355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_verifications_ibfk_1', 'user_email_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_email_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_email_verifications', type_='foreignkey')
    op.create_foreign_key('user_email_verifications_ibfk_1', 'user_email_verifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
