# Heroku dockerfile

# Pull base image
FROM python:3.10 as install-stage
# working directory in the container
WORKDIR /app
# copy dependency file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
# copy code
COPY . .

# launch app
FROM install-stage as serve-stage
CMD python main.py