"""added fields: name, profile_pic in user table

Revision ID: 56ae9ed1ba4e
Revises: fa7f7f93fb7c
Create Date: 2023-04-27 00:03:05.898419

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "56ae9ed1ba4e"
down_revision = "fa7f7f93fb7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=128), nullable=True))
    op.add_column(
        "users", sa.Column("profile_picture", sa.String(length=256), nullable=True)
    )
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_column("users", "profile_picture")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
