"""new table for admin app dev

Revision ID: a4cfdc5d543c
Revises: 56ae9ed1ba4e
Create Date: 2023-07-14 10:49:48.138045

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a4cfdc5d543c'
down_revision = '56ae9ed1ba4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=True),
    sa.Column('agent_email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('fav_posint', sa.Integer(), nullable=True),
    sa.Column('fav_posreal', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('flight_landing', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('on_holiday_for', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_agent_email'), 'trips', ['agent_email'], unique=True)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_agent_email'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
