name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      # - name: Add mysql password text file for a test mysql container
      #   run: echo "password" >> db/mysql_pwd.txt
      # - name: Run backend tests
      #   run: sudo ./script.sh run-api-tests
      # - name: Zip allure reports
      #   if: success() || failure()
      #   run: cd src/test && mv allure-results results && zip -r results.zip results
      # - name: Copy zipped reports to allure server
      #   if: success() || failure()
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST_DNS }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     port: 22
      #     source: "src/test/results.zip"
      #     target: "/home/ubuntu/allure-docker/projects/backend/"
      #     strip_components: 2
      # - name: Delete previous allure-results folder, unzip new one and delete zipped after
      #   if: success() || failure()
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_DNS }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     port: 22
      #     script: cd /home/ubuntu/allure-docker/projects/backend && sudo rm -rf results && unzip results.zip && rm results.zip
      # - name: Deploy to Server 1
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.HOST_DNS }}
      #     REMOTE_USER: ${{ secrets.USERNAME }}
      #     TARGET: ${{ secrets.TARGET_DIR }}
      - name: Restart app - build new containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: >-
            cd /home/ubuntu && 
            sudo rm -rf backend-fastapi-old && 
            mv backend-fastapi backend-fastapi-old &&
            git clone -b main https://github.com/mg-login-examples/login-backend-fastapi.git backend-fastapi &&
            cp backend-fastapi-old/db/mysql_pwd.txt backend-fastapi/db/ &&
            sudo rm -rf backend-fastapi-old &&
            cd backend-fastapi &&
            git clone -b main https://github.com/mg-login-examples/login-frontend-vue.git frontend &&
            ./script.sh launch-app-dev-env
# sudo ./script.sh launch-app
