name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API Tests And Send Results To Allure Docker Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Add mysql password text file for a test mysql container
        run: echo "password" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password" > docker_secrets/redis_pwd.txt
      - name: Run backend tests
        run: sudo ./scripts_docker.sh run-api-tests
      - name: Zip allure reports
        if: success() || failure()
        run: cd src/test && mv allure-results results && zip -r results.zip results
      - name: Copy zipped reports to allure server
        if: success() || failure()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "src/test/results.zip"
          target: "/home/ubuntu/allure-docker/projects/backend/"
          strip_components: 2
      - name: Delete previous allure-results folder, unzip new one and delete zipped after
        if: success() || failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: >-
            cd /home/ubuntu/allure-docker/projects/backend &&
            sudo rm -rf results &&
            unzip results.zip &&
            rm results.zip &&
            curl http://localhost:5050/allure-docker-service/generate-report?project_id=backend
  e2e-tests-cypress:
    name: Run Cypress E2E Tests And Send Results To Allure Docker Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Add mysql password text file for a test mysql container
        run: echo "password" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password" > docker_secrets/redis_pwd.txt
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: mg-login-examples/login-frontend-vue-vite
          path: frontend
      - name: Add github secret mailslurp api key as a text file used as a docker secret
        run: 'echo "$MAILSLURP_API_KEY" > frontend/docker_secrets/mailslurp_api_key.txt'
        shell: bash
        env:
          MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
      - name: Run cypress e2e tests
        run: ./scripts_docker.sh run-e2e-tests-cypress
      - name: Zip allure reports
        if: success() || failure()
        run: cd frontend/cypress && mv allure-results results && zip -r results.zip results
      - name: Copy zipped reports to allure server
        if: success() || failure()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "frontend/cypress/results.zip"
          target: "/home/ubuntu/allure-docker/projects/frontend-e2e-cypress/"
          strip_components: 2
      - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
        if: success() || failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: >-
            cd /home/ubuntu/allure-docker/projects/frontend-e2e-cypress &&
            sudo rm -rf results &&
            unzip results.zip &&
            rm results.zip &&
            curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e-cypress
  e2e-tests-playwright:
    name: Run Playwright E2E Tests And Send Results To Allure Docker Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Add mysql password text file for a test mysql container
        run: echo "password" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password" > docker_secrets/redis_pwd.txt
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: mg-login-examples/login-frontend-vue-vite
          path: frontend
      - name: Run playwright e2e tests
        run: ./scripts_docker.sh run-e2e-tests-playwright
      - name: Zip allure reports
        if: success() || failure()
        run: cd frontend/playwright && mv allure-results results && zip -r results.zip results
      - name: Copy zipped reports to allure server
        if: success() || failure()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "frontend/playwright/results.zip"
          target: "/home/ubuntu/allure-docker/projects/frontend-e2e-playwright/"
          strip_components: 2
      - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
        if: success() || failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: >-
            cd /home/ubuntu/allure-docker/projects/frontend-e2e-playwright &&
            sudo rm -rf results &&
            unzip results.zip &&
            rm results.zip &&
            curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e-playwright
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [api-tests, e2e-tests-cypress, e2e-tests-playwright]
    steps:
      - name: Restart app - build new containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: >-
            cd /home/ubuntu && 
            sudo rm -rf backend-fastapi-old && 
            mv backend-fastapi backend-fastapi-old &&
            git clone -b main https://github.com/mg-login-examples/login-backend-fastapi.git backend-fastapi &&
            cp backend-fastapi-old/docker_secrets/mysql_pwd.txt backend-fastapi/docker_secrets/ &&
            cp backend-fastapi-old/docker_secrets/mongo_pwd.txt backend-fastapi/docker_secrets/ &&
            cp backend-fastapi-old/docker_secrets/redis_pwd.txt backend-fastapi/docker_secrets/ &&
            sudo rm -rf backend-fastapi-old &&
            cd backend-fastapi &&
            git clone -b main https://github.com/mg-login-examples/login-frontend-vue-vite.git frontend &&
            ./scripts_docker.sh launch-api-cloud-dev
