name: Run Tests With Docker

on:
  push:
  workflow_dispatch:

jobs:
  api-tests-with-deps:
    name: Run API Tests with Docker using MySQL, Mongo, Redis based tokens, PubSub[Redis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Add mysql password text file for a test mysql container
        run: echo "password_mysql" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password_mongo" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password_redis" > docker_secrets/redis_pwd.txt
      - name: Run backend tests
        run: sudo ./scripts_docker.sh backend api-tests

  e2e-tests-cypress:
    name: Run Cypress E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Add mysql password text file for a test mysql container
        run: echo "password" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password" > docker_secrets/redis_pwd.txt
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: mg-login-examples/login-frontend-vue-vite
          path: frontend
      - name: Add github secret mailslurp api key as a text file used as a docker secret
        run: 'echo "$MAILSLURP_API_KEY" > frontend/docker_secrets/mailslurp_api_key.txt'
        shell: bash
        env:
          MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
      - name: Run cypress e2e tests
        run: ./scripts_docker.sh run-e2e-tests-cypress

  e2e-tests-playwright:
    name: Run Playwright E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Add mysql password text file for a test mysql container
        run: echo "password_mysql" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password_mongo" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password_redis" > docker_secrets/redis_pwd.txt
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: mg-login-examples/login-frontend-vue-vite
          path: frontend
      - name: Run playwright e2e tests
        run: ./scripts_docker.sh run-e2e-tests-playwright

  admin-app-e2e-tests-with-deps:
    name: Run Admin App E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Add mysql password text file for a test mysql container
        run: echo "password_mysql" > docker_secrets/mysql_pwd.txt
      - name: Add mongo password text file for a test mongo container
        run: echo "password_mongo" > docker_secrets/mongo_pwd.txt
      - name: Add redis password text file for a test redis container
        run: echo "password_redis" > docker_secrets/redis_pwd.txt
      - name: Run admin app e2e tests
        run: sudo ./scripts_docker.sh run-admin-app-e2e-tests
